version: '2'
services:
    kafka_demo-app:
        image: kafka_demo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kafka_demo-mysql:3306/kafka_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kafka_demo-mysql:
        extends:
            file: mysql.yml
            service: kafka_demo-mysql
